import React, { Component } from 'react';
import ContentCard from "./ContentCard"
class CardList extends Component {
  render() {
    return (
      <div>
        {data.map((post) => <ContentCard post={post} />)}      
      </div>
    );
  }
}

export default CardList;

const data = [
	{"title": "a purus. Duis elementum,", "content": "dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus.", "author": "Macey"},
	{"title": "nec, eleifend non, dapibus", "content": "ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel", "author": "Haviva"},
	{"title": "ullamcorper, nisl arcu iaculis", "content": "Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie", "author": "Mariko"},
	{"title": "bibendum sed, est. Nunc", "content": "felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus.", "author": "Abigail"},
	{"title": "Ut sagittis lobortis mauris.", "content": "auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,", "author": "Lois"},
	{"title": "tristique pellentesque, tellus sem", "content": "tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque.", "author": "Colin"},
	{"title": "Sed dictum. Proin eget", "content": "eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non,", "author": "Ray"},
	{"title": "non arcu. Vivamus sit", "content": "eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris", "author": "Laura"},
	{"title": "egestas rhoncus. Proin nisl", "content": "erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu", "author": "Ariana"},
	{"title": "mi. Duis risus odio,", "content": "urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas", "author": "Rana"},
	{"title": "In ornare sagittis felis.", "content": "semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod", "author": "Jordan"},
	{"title": "Quisque nonummy ipsum non", "content": "Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta", "author": "Pamela"},
	{"title": "ipsum. Suspendisse non leo.", "content": "non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer", "author": "Addison"},
	{"title": "Aliquam vulputate ullamcorper magna.", "content": "Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas", "author": "Kendall"},
	{"title": "gravida molestie arcu. Sed", "content": "tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus", "author": "Alika"},
	{"title": "aliquam, enim nec tempus", "content": "eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus", "author": "Illiana"},
	{"title": "Maecenas malesuada fringilla est.", "content": "Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat", "author": "India"},
	{"title": "tellus. Phasellus elit pede,", "content": "elit sed consequat auctor, nunc nulla vulputate dui, nec tempus", "author": "Aquila"},
	{"title": "faucibus orci luctus et", "content": "non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum", "author": "Elton"},
	{"title": "malesuada fames ac turpis", "content": "luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et", "author": "Donovan"},
	{"title": "In ornare sagittis felis.", "content": "mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam.", "author": "Mannix"},
	{"title": "tortor nibh sit amet", "content": "blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed", "author": "Ariel"},
	{"title": "eu dolor egestas rhoncus.", "content": "nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac,", "author": "Penelope"},
	{"title": "turpis. Nulla aliquet. Proin", "content": "consectetuer euismod est arcu ac orci. Ut semper pretium neque.", "author": "Ifeoma"},
	{"title": "auctor odio a purus.", "content": "non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna.", "author": "Hammett"},
	{"title": "placerat. Cras dictum ultricies", "content": "non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin", "author": "Calvin"},
	{"title": "Curabitur massa. Vestibulum accumsan", "content": "Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt,", "author": "Brett"},
	{"title": "blandit congue. In scelerisque", "content": "neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare", "author": "Matthew"},
	{"title": "magnis dis parturient montes,", "content": "Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce", "author": "Adrian"},
	{"title": "augue malesuada malesuada. Integer", "content": "Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante", "author": "Ursa"},
	{"title": "diam. Duis mi enim,", "content": "convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit", "author": "Gannon"},
	{"title": "lectus quis massa. Mauris", "content": "non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et,", "author": "Carissa"},
	{"title": "purus. Duis elementum, dui", "content": "et tristique pellentesque, tellus sem mollis dui, in sodales elit", "author": "Denise"},
	{"title": "magna, malesuada vel, convallis", "content": "tellus justo sit amet nulla. Donec non justo. Proin non massa non ante", "author": "Ulric"},
	{"title": "lorem tristique aliquet. Phasellus", "content": "nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id", "author": "Hector"},
	{"title": "pede, malesuada vel, venenatis", "content": "vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo", "author": "Macaulay"},
	{"title": "feugiat. Lorem ipsum dolor", "content": "nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat.", "author": "Charity"},
	{"title": "adipiscing, enim mi tempor", "content": "faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend.", "author": "William"},
	{"title": "Vestibulum ante ipsum primis", "content": "semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula", "author": "Colette"},
	{"title": "a odio semper cursus.", "content": "est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem,", "author": "Rhona"},
	{"title": "Fusce mi lorem, vehicula", "content": "Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed", "author": "Gannon"},
	{"title": "Aliquam adipiscing lobortis risus.", "content": "velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit", "author": "Zephr"},
	{"title": "rutrum, justo. Praesent luctus.", "content": "Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices", "author": "Jane"},
	{"title": "Mauris eu turpis. Nulla", "content": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere", "author": "Ima"},
	{"title": "placerat. Cras dictum ultricies", "content": "Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis", "author": "Indigo"},
	{"title": "sit amet, consectetuer adipiscing", "content": "Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede", "author": "Eve"},
	{"title": "pellentesque, tellus sem mollis", "content": "mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam", "author": "Yoshio"},
	{"title": "lectus. Cum sociis natoque", "content": "vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris", "author": "Rooney"},
	{"title": "ac mattis velit justo", "content": "egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue", "author": "Baxter"},
	{"title": "lorem eu metus. In", "content": "ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget", "author": "Jackson"},
	{"title": "arcu. Aliquam ultrices iaculis", "content": "pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan", "author": "Brandon"},
	{"title": "per inceptos hymenaeos. Mauris", "content": "libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis", "author": "Cameran"},
	{"title": "luctus aliquet odio. Etiam", "content": "mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum", "author": "Zenia"},
	{"title": "tempus, lorem fringilla ornare", "content": "elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat", "author": "Astra"},
	{"title": "ac turpis egestas. Aliquam", "content": "mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor", "author": "Vivien"},
	{"title": "erat, eget tincidunt dui", "content": "nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante.", "author": "Cailin"},
	{"title": "enim diam vel arcu.", "content": "rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem,", "author": "Callum"},
	{"title": "Aliquam fringilla cursus purus.", "content": "Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus", "author": "Ethan"},
	{"title": "Nunc mauris elit, dictum", "content": "parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc", "author": "Herman"},
	{"title": "in, tempus eu, ligula.", "content": "a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque", "author": "Vincent"},
	{"title": "vitae odio sagittis semper.", "content": "Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus", "author": "Blythe"},
	{"title": "purus. Maecenas libero est,", "content": "aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris", "author": "Clinton"},
	{"title": "Nam ac nulla. In", "content": "dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus", "author": "Finn"},
	{"title": "dui lectus rutrum urna,", "content": "id risus quis diam luctus lobortis. Class aptent taciti sociosqu", "author": "Beck"},
	{"title": "iaculis quis, pede. Praesent", "content": "montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit.", "author": "Alea"},
	{"title": "velit. Pellentesque ultricies dignissim", "content": "et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida", "author": "Amir"},
	{"title": "cursus. Nunc mauris elit,", "content": "tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget,", "author": "Shannon"},
	{"title": "Phasellus ornare. Fusce mollis.", "content": "Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec,", "author": "Aretha"},
	{"title": "non quam. Pellentesque habitant", "content": "sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu,", "author": "Oleg"},
	{"title": "pede et risus. Quisque", "content": "elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit", "author": "Samson"},
	{"title": "Phasellus nulla. Integer vulputate,", "content": "sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque", "author": "Nora"},
	{"title": "magna. Praesent interdum ligula", "content": "lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc.", "author": "Olivia"},
	{"title": "pede. Cum sociis natoque", "content": "nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras", "author": "Warren"},
	{"title": "semper et, lacinia vitae,", "content": "auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus.", "author": "Eagan"},
	{"title": "dapibus gravida. Aliquam tincidunt,", "content": "non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non,", "author": "Griffith"},
	{"title": "nisi dictum augue malesuada", "content": "enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros", "author": "Dai"},
	{"title": "sed, facilisis vitae, orci.", "content": "Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at", "author": "Kelly"},
	{"title": "luctus vulputate, nisi sem", "content": "mauris a nunc. In at pede. Cras vulputate velit eu sem.", "author": "Ferdinand"},
	{"title": "eu odio tristique pharetra.", "content": "gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi", "author": "Channing"},
	{"title": "purus gravida sagittis. Duis", "content": "sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin", "author": "Fletcher"},
	{"title": "lorem, eget mollis lectus", "content": "dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum", "author": "Melodie"},
	{"title": "mi felis, adipiscing fringilla,", "content": "elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin", "author": "Victor"},
	{"title": "ornare lectus justo eu", "content": "tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,", "author": "Reuben"},
	{"title": "interdum libero dui nec", "content": "velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium", "author": "Serina"},
	{"title": "Morbi metus. Vivamus euismod", "content": "a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin", "author": "Abraham"},
	{"title": "Aliquam erat volutpat. Nulla", "content": "Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero", "author": "Thomas"},
	{"title": "adipiscing lobortis risus. In", "content": "tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis", "author": "Knox"},
	{"title": "elit sed consequat auctor,", "content": "et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas", "author": "Connor"},
	{"title": "dolor. Quisque tincidunt pede", "content": "molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,", "author": "Alvin"},
	{"title": "dictum mi, ac mattis", "content": "iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum", "author": "Mikayla"},
	{"title": "faucibus orci luctus et", "content": "mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet", "author": "Abraham"},
	{"title": "Morbi neque tellus, imperdiet", "content": "Sed nunc est, mollis non, cursus non, egestas a, dui. Cras", "author": "Orson"},
	{"title": "libero. Morbi accumsan laoreet", "content": "in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla", "author": "Luke"},
	{"title": "semper erat, in consectetuer", "content": "et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie", "author": "Erica"},
	{"title": "Cras convallis convallis dolor.", "content": "molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu", "author": "Xanthus"},
	{"title": "venenatis lacus. Etiam bibendum", "content": "Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu.", "author": "Kermit"},
	{"title": "Nullam scelerisque neque sed", "content": "cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula", "author": "Lyle"},
	{"title": "dis parturient montes, nascetur", "content": "elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus", "author": "Mark"},
	{"title": "placerat eget, venenatis a,", "content": "Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros.", "author": "Chaney"},
	{"title": "dui. Cras pellentesque. Sed", "content": "Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante", "author": "Judith"}
];